all: Shell379 sleeper runner

Shell379: Shell379.cpp
	g++ -o Shell379 Shell379.cpp

sleeper: sleeper.cpp
	g++ -o sleeper sleeper.cpp

runner: runner.cpp
	g++ -o runner runner.cpp

clean:
	rm -f Shell379 sleeper runner